### ISSUE TITLE
getting port error

### ISSUE THREAD

**Issue by rishabhmodi03** [yash-dk/TorToolkit-Telegram#116]
it gives me an error

Error: '' is not a valid port number.

2021-11-11 18:28:30,890 INFO MainThread root Database created
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/torapp/tortoolkit/__init__.py", line 19, in <module>
    upload_db = TtkUpload()
  File "/torapp/tortoolkit/core/database_handle.py", line 116, in __init__
    super().__init__(dburl)
  File "/torapp/tortoolkit/functions/pg_plugin.py", line 28, in __init__
    self._conn = psycopg2.connect(self._dburl)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

Exception ignored in: <function TtkUpload.__del__ at 0x7f0db9c43160>
Traceback (most recent call last):
  File "/torapp/tortoolkit/core/database_handle.py", line 218, in __del__
    super().__del__()
  File "/torapp/tortoolkit/functions/pg_plugin.py", line 74, in __del__
    self._connection_users.pop()
IndexError: pop from empty list
Removing intermediate container 8e7334a75c7c
The command '/bin/sh -c ./start.sh' returned a non-zero code: 1

i am a noob do not have much knowledge.

**Comment by santosadrian** [comment]
same here, I tried everything. I put export PORT=80 in .bashrc and also before starting bot... 

did you solved it?
