### ISSUE TITLE
Index error:pop from empty list

### ISSUE THREAD

**Issue by Eagletech001** [yash-dk/TorToolkit-Telegram#118]
kit-telegram_tortk_1 exited with code 1
tortk_1  | 
tortk_1  | Error: '' is not a valid port number.
tortk_1  | 
tortk_1  | 2021-12-12 13:23:39,462 INFO MainThread root Database created
tortk_1  | Traceback (most recent call last):
tortk_1  |   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
tortk_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
tortk_1  |   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
tortk_1  |     return _get_module_details(pkg_main_name, error)
tortk_1  |   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
tortk_1  |     __import__(pkg_name)
tortk_1  |   File "/torapp/tortoolkit/__init__.py", line 19, in <module>
tortk_1  |     upload_db = TtkUpload()
tortk_1  |   File "/torapp/tortoolkit/core/database_handle.py", line 116, in __init__
tortk_1  |     super().__init__(dburl)
tortk_1  |   File "/torapp/tortoolkit/functions/pg_plugin.py", line 28, in __init__tortk_1  |     self._conn = psycopg2.connect(self._dburl)
tortk_1  |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
tortk_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
tortk_1  | psycopg2.OperationalError: could not connect to server: Connection refused
tortk_1  | Is the server running on host "127.0.0.1" and accepting
tortk_1  | TCP/IP connections on port 5432?
tortk_1  | 
tortk_1  | Exception ignored in: <function TtkUpload.__del__ at 0x7fab5bcf5700>
tortk_1  | Traceback (most recent call last):
tortk_1  |   File "/torapp/tortoolkit/core/database_handle.py", line 218, in __del__
tortk_1  |     super().__del__()
tortk_1  |   File "/torapp/tortoolkit/functions/pg_plugin.py", line 74, in __del__
tortk_1  |     self._connection_users.pop()
tortk_1  | IndexError: pop from empty list
tortoolkit-telegram_tortk_1 exited with code 1

**Comment by santosadrian** [comment]
did you solved it? I have the same error
