### ISSUE TITLE
Hello,how to fill in ALD_USR and OWNER_ID? Can you give an example?

### ISSUE THREAD

**Issue by Mpk2022** [yash-dk/TorToolkit-Telegram#120]
ALD_USR = [5052*****，-1001607****]
        OWNER_ID = 5052****
Is this correct?
If this is filled in, an error will be reported.
[2022-02-03 20:10:01 +0530] [6] [INFO] Starting gunicorn 20.0.4
tortk_1  | [2022-02-03 20:10:01 +0530] [6] [INFO] Listening at: http://0.0.0.0:80 (6)
tortk_1  | [2022-02-03 20:10:01 +0530] [6] [INFO] Using worker: aiohttp.GunicornWebWorker
tortk_1  | [2022-02-03 20:10:01 +0530] [10] [INFO] Booting worker with pid: 10
tortk_1  | Traceback (most recent call last):
tortk_1  |   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
tortk_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
tortk_1  |   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
tortk_1  |     return _get_module_details(pkg_main_name, error)
tortk_1  |   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
tortk_1  |     __import__(pkg_name)
tortk_1  |   File "/torapp/tortoolkit/__init__.py", line 13, in <module>
tortk_1  |     from tortoolkit.core.wserver import start_server
tortk_1  |   File "/torapp/tortoolkit/core/wserver.py", line 7, in <module>
tortk_1  |     from .database_handle import TtkTorrents
tortk_1  |   File "/torapp/tortoolkit/core/database_handle.py", line 7, in <module>
tortk_1  |     from ..consts.ExecVarsSample import ExecVars
tortk_1  |   File "/torapp/tortoolkit/consts/ExecVarsSample.py", line 17
tortk_1  |     ALD_USR = [505********，-1001*********]

**Comment by chiragtestt** [comment]
ALD_USR = [5052*****,-1001607****]
OWNER_ID = 5052****

Don't give space in ALD_USR after comma
