### ISSUE TITLE
Torrent Uploading Failed :/

### ISSUE THREAD

**Issue by nxthsara** [yash-dk/TorToolkit-Telegram#18]
2021-01-31 09:15:22,800 INFO MainThread tortoolkit.functions.QBittorrentWrap Trying to login in qBittorrent using creds localhost 8090 admin adminadmin
2021-01-31 09:15:22,905 INFO MainThread tortoolkit.functions.QBittorrentWrap Client connected successfully to the torrent server. :)
2021-01-31 09:15:23,107 INFO MainThread tortoolkit.functions.QBittorrentWrap True
2021-01-31 09:15:23,107 INFO MainThread tortoolkit.functions.QBittorrentWrap Trying to login in qBittorrent using creds localhost 8090 admin adminadmin
2021-01-31 09:15:23,217 INFO MainThread tortoolkit.functions.QBittorrentWrap Client connected successfully to the torrent server. :)
2021-01-31 09:15:23,497 ERROR MainThread telethon.client.updates Unhandled exception on handle_leech_command
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/updates.py", line 446, in _dispatch_update
    await callback(event)
  File "/torapp/tortoolkit/core/HandleManager.py", line 236, in handle_leech_command
    await check_link(e,rclone, is_zip, is_ext)
  File "/torapp/tortoolkit/functions/Leech_Module.py", line 134, in check_link
    path = await QBittorrentWrap.register_torrent(mgt,rmess,omess,True)
  File "/torapp/tortoolkit/functions/QBittorrentWrap.py", line 375, in register_torrent
    if torrent.progress == 1:
AttributeError: 'bool' object has no attribute 'progress'
2021-01-31 09:15:27,620 INFO MainThread tortoolkit.functions.QBittorrentWrap Trying to login in qBittorrent using creds localhost 8090 admin adminadmin
2021-01-31 09:15:27,775 INFO MainThread tortoolkit.functions.QBittorrentWrap Client connected successfully to the torrent server. :)

**Comment by yash-dk** [comment]
What's the platform? Whats the size of the stuff you were downloading?
