### ISSUE TITLE
😐😐😐😐😐

### ISSUE THREAD

**Issue by premiumfile** [yash-dk/TorToolkit-Telegram#35]
[2021-03-01 13:02:13 +0000] [129284] [INFO] Starting gunicorn 20.0.4
[2021-03-01 13:02:13 +0000] [129284] [ERROR] Connection in use: ('0.0.0.0', 80)
[2021-03-01 13:02:13 +0000] [129284] [ERROR] Retrying in 1 second.
2021-03-01 13:02:13,414 INFO MainThread root Database created
2021-03-01 13:02:13,449 INFO MainThread telethon.crypto.aes cryptg detected, it will be used for encryption
2021-03-01 13:02:14,051 INFO MainThread pyrogram.crypto.aes Using TgCrypto
[2021-03-01 13:02:14 +0000] [129284] [ERROR] Connection in use: ('0.0.0.0', 80)
[2021-03-01 13:02:14 +0000] [129284] [ERROR] Retrying in 1 second.
2021-03-01 13:02:14,420 INFO MainThread root Telethon Client created.
Pyrogram v1.0.2, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

2021-03-01 13:02:15,048 INFO MainThread root Started 100 HandlerTasks
2021-03-01 13:02:15,052 INFO MainThread root Pryogram Client created.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/TorToolkit-Telegram/tortoolkit/__main__.py", line 46, in <module>
    ttkbot.loop.run_until_complete(start_server_async(get_val("SERVPORT")))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/TorToolkit-Telegram/tortoolkit/core/wserver.py", line 334, in start_server_async
    await web.TCPSite(runner,"0.0.0.0",port).start()
  File "/home/ubuntu/venv/lib/python3.8/site-packages/aiohttp/web_runner.py", line 100, in start
    self._server = await loop.create_server(  # type: ignore
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 80): address already in use
(venv) root@ip-172-31-44-173:/home/ubuntu/TorToolkit-Telegram# [2021-03-01 13:02:15 +0000] [129284] [ERROR] Connection in use: ('0.0.0.0', 80)
[2021-03-01 13:02:15 +0000] [129284] [ERROR] Retrying in 1 second.
[2021-03-01 13:02:16 +0000] [129284] [ERROR] Connection in use: ('0.0.0.0', 80)
[2021-03-01 13:02:16 +0000] [129284] [ERROR] Retrying in 1 second.
(venv) root@ip-172-31-44-173:/home/ubuntu/TorToolkit-Telegram# [2021-03-01 13:02:17 +0000] [129284] [ERROR] Connection in use: ('0.0.0.0', 80)
[2021-03-01 13:02:17 +0000] [129284] [ERROR] Retrying in 1 second.
[2021-03-01 13:02:18 +0000] [129284] [ERROR] Can't connect to ('0.0.0.0', 80)

**Comment by yash-dk** [comment]
Where are you trying to deploy??
Join https://t.me/ttkdisc to get support more quickly.
